/**
 * Yaturu
 * ## Welcome  This is a place to put general notes and extra information, for 
 * internal use.  To get started designing/documenting this API, select a version on the left. ## Welcome 
 *  This is a place to put general notes and extra information, for internal use. 
 *  To get started designing/documenting this API, select a version on the left.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Inject, Injectable, Optional } from '@angular/core';
import { Http, Headers, URLSearchParams } from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response } from '@angular/http';

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models from '../model/models';
import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class ContentApi {
    protected basePath = 'https://yaturu-test-server.appspot.com/_ah/api';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
        this.defaultHeaders.set('Content-Type', 'application/json');

    }

	/**
     * 
     * Extends object by coping non-existing properties.
     * @param objA object to be extended
     * @param objB source object
     */
    private extendObj<T1, T2>(objA: T1, objB: T2) {
        for (let key in objB) {
            if (objB.hasOwnProperty(key)) {
                objA[key] = objB[key];
            }
        }
        return <T1 & T2>objA;
    }

    /**
     * deleteContent
     * 
     * @param contentKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public dELETEContentContentKey(contentKey: string, authorization: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.dELETEContentContentKeyWithHttpInfo(contentKey, authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getAllContent
     * 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETContent(authorization: string, extraHttpRequestParams?: any): Observable<Array<models.Content>> {
        return this.gETContentWithHttpInfo(authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getAnswer
     * getAnswer
     * @param questionKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETContentAnswerQuestionQuestionKey(questionKey: string, authorization: string, extraHttpRequestParams?: any): Observable<any> {
        return this.gETContentAnswerQuestionQuestionKeyWithHttpInfo(questionKey, authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * sendAnswer
     * sendAnswer is a function run by the Tourist when he has a question to answer.
     * @param questionKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pOSTContentAnswerQuestionQuestionkey(questionKey: string,
        authorization: string, body?: models.AnswerWrapper, extraHttpRequestParams?: any): Observable<{}> {
        return this.pOSTContentAnswerQuestionQuestionkeyWithHttpInfo(questionKey, authorization, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * updateContent
     * 
     * @param contentKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pOSTContentContentKey(contentKey: string, authorization: string,
        body?: models.Content, extraHttpRequestParams?: any): Observable<{}> {
        return this.pOSTContentContentKeyWithHttpInfo(contentKey, authorization, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * sendContent
     * sendContent
     * @param contentKey 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public pOSTContentContentKeyGuideGuideKey(contentKey: string, tripKey: string,
        authorization: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.pOSTContentContentKeyGuideGuideKeyWithHttpInfo(contentKey, tripKey, authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * sendMessage
     * sendMessage
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pOSTContentMessageGuideGuideKey(tripKey: string, authorization: string,
        body?: models.MessageWrapper, extraHttpRequestParams?: any): Observable<{}> {
        return this.pOSTContentMessageGuideGuideKeyWithHttpInfo(tripKey, authorization, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * createContent
     * 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pUTContent(authorization: string, body?: models.Content, extraHttpRequestParams?: any): Observable<models.KeyWrapper> {
        return this.pUTContentWithHttpInfo(authorization, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * createAndSendCustomQuestion
     * 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pUTContentTripTripKey(tripKey: string, authorization: string,
        body?: models.ContentClient, extraHttpRequestParams?: any): Observable<models.KeyWrapper> {
        return this.pUTContentTripTripKeyWithHttpInfo(tripKey, authorization, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * deleteContent
     * 
     * @param contentKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public dELETEContentContentKeyWithHttpInfo(contentKey: string,
        authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/content/${contentKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'contentKey' is not null or undefined
        if (contentKey === null || contentKey === undefined) {
            throw new Error('Required parameter contentKey was null or undefined when calling dELETEContentContentKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling dELETEContentContentKey.');
        }
        headers.set('Authorization', String(authorization));
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];





        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getAllContent
     * 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETContentWithHttpInfo(authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/content`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling gETContent.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];





        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getAnswer
     * getAnswer
     * @param questionKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETContentAnswerQuestionQuestionKeyWithHttpInfo(questionKey: string,
        authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/content/answer/question/${questionKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'questionKey' is not null or undefined
        if (questionKey === null || questionKey === undefined) {
            throw new Error('Required parameter questionKey was null or undefined when calling gETContentAnswerQuestionQuestionKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling gETContentAnswerQuestionQuestionKey.');
        }
        headers.set('Authorization', String(authorization));
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];





        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * sendAnswer
     * sendAnswer is a function run by the Tourist when he has a question to answer.
     * @param questionKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pOSTContentAnswerQuestionQuestionkeyWithHttpInfo(questionKey: string,
        authorization: string, body?: models.AnswerWrapper, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/content/answer/question/${questionKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'questionKey' is not null or undefined
        if (questionKey === null || questionKey === undefined) {
            throw new Error('Required parameter questionKey was null or undefined when calling pOSTContentAnswerQuestionQuestionkey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pOSTContentAnswerQuestionQuestionkey.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * updateContent
     * 
     * @param contentKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pOSTContentContentKeyWithHttpInfo(contentKey: string, authorization: string,
        body?: models.Content, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/content/${contentKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'contentKey' is not null or undefined
        if (contentKey === null || contentKey === undefined) {
            throw new Error('Required parameter contentKey was null or undefined when calling pOSTContentContentKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pOSTContentContentKey.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * sendContent
     * sendContent
     * @param contentKey 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public pOSTContentContentKeyGuideGuideKeyWithHttpInfo(contentKey: string, tripKey: string,
        authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/content/${contentKey}/trip/${tripKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'contentKey' is not null or undefined
        if (contentKey === null || contentKey === undefined) {
            throw new Error('Required parameter contentKey was null or undefined when calling pOSTContentContentKeyGuideGuideKey.');
        }
        // verify required parameter 'tripKey' is not null or undefined
        if (tripKey === null || tripKey === undefined) {
            throw new Error('Required parameter tripKey was null or undefined when calling pOSTContentContentKeyGuideGuideKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pOSTContentContentKeyGuideGuideKey.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * sendMessage
     * sendMessage
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pOSTContentMessageGuideGuideKeyWithHttpInfo(tripKey: string, authorization: string,
        body?: models.MessageWrapper, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/content/message/trip/${tripKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'tripKey' is not null or undefined
        if (tripKey === null || tripKey === undefined) {
            throw new Error('Required parameter tripKey was null or undefined when calling pOSTContentMessageGuideGuideKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pOSTContentMessageGuideGuideKey.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * createContent
     * 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pUTContentWithHttpInfo(authorization: string, body?: models.Content, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/content`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pUTContent.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * createAndSendCustomQuestion
     * 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pUTContentTripTripKeyWithHttpInfo(tripKey: string, authorization: string,
        body?: models.ContentClient, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/content/trip/${tripKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'tripKey' is not null or undefined
        if (tripKey === null || tripKey === undefined) {
            throw new Error('Required parameter tripKey was null or undefined when calling pUTContentTripTripKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pUTContentTripTripKey.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
