/**
 * Yaturu
 * ## Welcome  This is a place to put general notes and extra information,
 *  for internal use.  To get started designing/documenting this API, 
 * select a version on the left. ## Welcome  This is a place to put general notes and extra information,
 *  for internal use.  To get started designing/documenting this API, select a version on the left.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Inject, Injectable, Optional } from '@angular/core';
import { Http, Headers, URLSearchParams } from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response } from '@angular/http';

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models from '../model/models';
import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class GuideApi {
    protected basePath = 'https://yaturu-test-server.appspot.com/_ah/api';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
        this.defaultHeaders.set('Content-Type', 'application/json');


    }

	/**
     * 
     * Extends object by coping non-existing properties.
     * @param objA object to be extended
     * @param objB source object
     */
    private extendObj<T1, T2>(objA: T1, objB: T2) {
        for (let key in objB) {
            if (objB.hasOwnProperty(key)) {
                objA[key] = objB[key];
            }
        }
        return <T1 & T2>objA;
    }

    /**
     * deleteGuide
     * 
     * @param guideKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public dELETEGuideGuideKey(guideKey: string, authorization: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.dELETEGuideGuideKeyWithHttpInfo(guideKey, authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getAllGuides
     * returns all guides without full trip data
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETGuide(authorization: string, extraHttpRequestParams?: any): Observable<Array<models.Guide>> {
        return this.gETGuideWithHttpInfo(authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getLatestGuideByTrip
     * 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETGuideTripTripKey(tripKey: string, authorization: string, extraHttpRequestParams?: any): Observable<models.Guide> {
        return this.gETGuideTripTripKeyWithHttpInfo(tripKey, authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * updateGuide
     * 
     * @param guideKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pOSTGuideGuideKey(guideKey: string, authorization: string, body?: models.Guide, extraHttpRequestParams?: any): Observable<any> {
        return this.pOSTGuideGuideKeyWithHttpInfo(guideKey, authorization, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * assignGuideToTrip
     * 
     * @param guideKey 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public pOSTGuideGuideKeyTripTripKey(guideKey: string, tripKey: string, authorization: string,
        extraHttpRequestParams?: any): Observable<{}> {
        return this.pOSTGuideGuideKeyTripTripKeyWithHttpInfo(guideKey, tripKey, authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * guideLogin
     * login
     * @param body 
     */
    public pOSTGuideLogin(body?: models.SignInWrapper, extraHttpRequestParams?: any): Observable<models.TokenAndGuideAndRegionsWrapper> {
        return this.pOSTGuideLoginWithHttpInfo(body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * createGuide
     * 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pUTGuide(authorization: string, body?: models.GuideAndPasswordWrapper,
        extraHttpRequestParams?: any): Observable<models.KeyWrapper> {
        return this.pUTGuideWithHttpInfo(authorization, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    public postResetPassword(authorization: string, body?, extraHttpRequestParams?: any): Observable<any> {
        return this.postResetPasswordWithHttpInfo(authorization, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * signUpGuide
     * signUp
     * @param body 
     */
    public pUTGuideSignup(body?: models.GuideAndPasswordWrapper,
        extraHttpRequestParams?: any): Observable<models.TokenAndGuideAndRegionsWrapper> {
        return this.pUTGuideSignupWithHttpInfo(body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * deleteGuide
     * 
     * @param guideKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public dELETEGuideGuideKeyWithHttpInfo(guideKey: string, authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/guide/${guideKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'guideKey' is not null or undefined
        if (guideKey === null || guideKey === undefined) {
            throw new Error('Required parameter guideKey was null or undefined when calling dELETEGuideGuideKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling dELETEGuideGuideKey.');
        }
        headers.set('Authorization', String(authorization));


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];





        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getAllGuides
     * returns all guides without full trip data
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETGuideWithHttpInfo(authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/guide`;
        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling gETGuide.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];





        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getLatestGuideByTrip
     * 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETGuideTripTripKeyWithHttpInfo(tripKey: string, authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/guide/trip/${tripKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'tripKey' is not null or undefined
        if (tripKey === null || tripKey === undefined) {
            throw new Error('Required parameter tripKey was null or undefined when calling gETGuideTripTripKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling gETGuideTripTripKey.');
        }
        headers.set('Authorization', String(authorization));


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];





        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * updateGuide
     * 
     * @param guideKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pOSTGuideGuideKeyWithHttpInfo(guideKey: string, authorization: string,
        body?: models.Guide, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/guide/${guideKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'guideKey' is not null or undefined
        if (guideKey === null || guideKey === undefined) {
            throw new Error('Required parameter guideKey was null or undefined when calling pOSTGuideGuideKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pOSTGuideGuideKey.');
        }
        headers.set('Authorization', String(authorization));


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * assignGuideToTrip
     * 
     * @param guideKey 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public pOSTGuideGuideKeyTripTripKeyWithHttpInfo(guideKey: string,
        tripKey: string, authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/guide/${guideKey}/trip/${tripKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'guideKey' is not null or undefined
        if (guideKey === null || guideKey === undefined) {
            throw new Error('Required parameter guideKey was null or undefined when calling pOSTGuideGuideKeyTripTripKey.');
        }
        // verify required parameter 'tripKey' is not null or undefined
        if (tripKey === null || tripKey === undefined) {
            throw new Error('Required parameter tripKey was null or undefined when calling pOSTGuideGuideKeyTripTripKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pOSTGuideGuideKeyTripTripKey.');
        }
        headers.set('Authorization', String(authorization));


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];





        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * guideLogin
     * login
     * @param body 
     */
    public pOSTGuideLoginWithHttpInfo(body?: models.SignInWrapper, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/guide/login`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * createGuide
     * 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pUTGuideWithHttpInfo(authorization: string, body?: models.GuideAndPasswordWrapper,
        extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/guide`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pUTGuide.');
        }
        headers.set('Authorization', String(authorization));


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }
    
    public postResetPasswordWithHttpInfo(authorization: string, body?,
        extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/guide/password`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pUTGuide.');
        }
        headers.set('Authorization', String(authorization));


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * signUpGuide
     * signUp
     * @param body 
     */
    public pUTGuideSignupWithHttpInfo(body?: models.GuideAndPasswordWrapper, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/guide/signup`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
