/**
 * Yaturu
 * ## Welcome  This is a place to put general notes and extra information,
 *  for internal use.  To get started designing/documenting this API,
 *  select a version on the left. ## Welcome  This is a place to put general notes and extra information,
 *  for internal use.  To get started designing/documenting this API, select a version on the left.
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Inject, Injectable, Optional } from '@angular/core';
import { Http, Headers, URLSearchParams } from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response } from '@angular/http';

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models from '../model/models';
import { BASE_PATH } from '../variables';
import { Configuration } from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class TripApi {
    protected basePath = 'https://yaturu-test-server.appspot.com/_ah/api';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
        this.defaultHeaders.set('Content-Type', 'application/json');
    }

	/**
     * 
     * Extends object by coping non-existing properties.
     * @param objA object to be extended
     * @param objB source object
     */
    private extendObj<T1, T2>(objA: T1, objB: T2) {
        for (let key in objB) {
            if (objB.hasOwnProperty(key)) {
                objA[key] = objB[key];
            }
        }
        return <T1 & T2>objA;
    }

    /**
     * deleteTrip
     * 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public dELETETripTripKey(tripKey: string, authorization: string, extraHttpRequestParams?: any): Observable<{}> {
        return this.dELETETripTripKeyWithHttpInfo(tripKey, authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    public getUrlDownloadTrip(tripKey: string, authorization: string, extraHttpRequestParams?: any): Observable<any> {
        return this.getUrlDownloadTripWithHttpInfo(tripKey, authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getFutureTrips
     * 
     */
    public gETTripFuture(extraHttpRequestParams?: any): Observable<Array<models.TripClient>> {
        return this.gETTripFutureWithHttpInfo(extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getTripsAndRegionsByGuide
     * getAllTrip
     * @param guideKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETTripGuideGuideKey(guideKey: string, authorization: string,
        extraHttpRequestParams?: any): Observable<models.TripsAndRegionsWrapper> {
        return this.gETTripGuideGuideKeyWithHttpInfo(guideKey, authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * getAllTrip
     * getTrip
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETTripTripKey(authorization: string, extraHttpRequestParams?: any): Observable<Array<models.Trip>> {
        return this.gETTripTripKeyWithHttpInfo(authorization, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * updateTrip
     * 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pOSTTripTripKey(tripKey: string, authorization: string, body?: models.Trip, extraHttpRequestParams?: any): Observable<{}> {
        return this.pOSTTripTripKeyWithHttpInfo(tripKey, authorization, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }

    /**
     * createTrip
     * 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pUTTrip(authorization: string, body?: models.Trip, extraHttpRequestParams?: any): Observable<models.KeyWrapper> {
        return this.pUTTripWithHttpInfo(authorization, body, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json();
                }
            });
    }


    /**
     * deleteTrip
     * 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public dELETETripTripKeyWithHttpInfo(tripKey: string, authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/trip/${tripKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'tripKey' is not null or undefined
        if (tripKey === null || tripKey === undefined) {
            throw new Error('Required parameter tripKey was null or undefined when calling dELETETripTripKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling dELETETripTripKey.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Delete,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getFutureTrips
     * 
     */
    public gETTripFutureWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/trip/future`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845


        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];





        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getTripsAndRegionsByGuide
     * getAllTrip
     * @param guideKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETTripGuideGuideKeyWithHttpInfo(guideKey: string, authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/trip/guide/${guideKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'guideKey' is not null or undefined
        if (guideKey === null || guideKey === undefined) {
            throw new Error('Required parameter guideKey was null or undefined when calling gETTripGuideGuideKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling gETTripGuideGuideKey.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];





        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * getAllTrip
     * getTrip
     * @param authorization token with \&quot;Bearer \&quot; prefix
     */
    public gETTripTripKeyWithHttpInfo(authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/trip`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling gETTripTripKey.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];





        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    public getUrlDownloadTripWithHttpInfo(tripKey: string, authorization: string, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/trip/${tripKey}/questions`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling gETTripTripKey.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Get,
            headers: headers,
            search: queryParameters,
            body: ''
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * updateTrip
     * 
     * @param tripKey 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pOSTTripTripKeyWithHttpInfo(tripKey: string, authorization: string,
        body?: models.Trip, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/trip/${tripKey}`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'tripKey' is not null or undefined
        if (tripKey === null || tripKey === undefined) {
            throw new Error('Required parameter tripKey was null or undefined when calling pOSTTripTripKey.');
        }
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pOSTTripTripKey.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * createTrip
     * 
     * @param authorization token with \&quot;Bearer \&quot; prefix
     * @param body 
     */
    public pUTTripWithHttpInfo(authorization: string, body?: models.Trip, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + `/trip`;

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // verify required parameter 'authorization' is not null or undefined
        if (authorization === null || authorization === undefined) {
            throw new Error('Required parameter authorization was null or undefined when calling pUTTrip.');
        }
        headers.set('Authorization', String(authorization));

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        // to determine the Accept header
        let produces: string[] = [
            'application/json'
        ];



        headers.set('Content-Type', 'application/json');


        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Put,
            headers: headers,
            body: body == null ? '' : JSON.stringify(body), // https://github.com/angular/angular/issues/10612
            search: queryParameters
        });

        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = this.extendObj(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
